markdown.lo: /home/kevin/Documents/Projects/PHP_MARKDOWN/markdown.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/kevin/Documents/Projects/PHP_MARKDOWN $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/kevin/Documents/Projects/PHP_MARKDOWN/markdown.c -o markdown.lo 
$(phplibdir)/markdown.la: ./markdown.la
	$(LIBTOOL) --mode=install cp ./markdown.la $(phplibdir)

./markdown.la: $(shared_objects_markdown) $(MARKDOWN_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_markdown) $(MARKDOWN_SHARED_LIBADD)

